Repository claudiiafg/MapConU, pull requests merged in 2020-03, with the labels that each got.

#127 Tests/86 e2e protractor tests
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
Labels: Ready for review, risk: small, sprint 2, testing

#132 Feature/21 alternative routes
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/outdoor/google-map/google-map.component.html
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/popovers/search-popover/search-popover.component.ts
  src/app/components/popovers/time-footer/time-footer.component.ts
  src/services/direction.service.ts
Labels: Ready for review, priority 3, risk: medium, sprint 2

#134 Set close button + styling
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.scss
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/popovers/time-footer/time-footer.component.html
  src/app/components/popovers/time-footer/time-footer.component.scss
Labels: Ready for review, priority 1, risk: small, sprint 2

#135 Auto complete + viewpoint change on search location done
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
Labels: Ready for review, priority 1, risk: small, sprint 2

#136 css fix to buttons to display side by side instead of on top of each …
  src/global.scss
Labels: Ready for review, bug

#133 Tests/unit tests
  karma.conf.js
  package.json
  src/app/app.component.spec.ts
  src/app/components/indoor/indoor-map/indoor-map.component.spec.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.spec.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.spec.ts
  src/app/components/outdoor/google-map/google-map.component.spec.ts
  src/app/components/outdoor/modal-directions/modal-directions.component.spec.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.spec.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.spec.ts
  src/app/components/popovers/poi-popover/poi-popover.component.spec.ts
  src/app/components/popovers/search-popover/search-popover.component.spec.ts
  src/app/components/popovers/time-footer/time-footer.component.spec.ts
  src/app/components/settings-toolbar/settings-toolbar.component.spec.ts
  src/app/pages/indoor-view/indoor-view.page.spec.ts
  src/app/pages/outdoor-view/outdoor-view.page.spec.ts
  src/services/geolocation.services.ts
  src/services/poi.services.ts
Labels: WIP, priority 1, sprint 2, testing

#139 Fix small bug with alternate path
  src/app/components/outdoor/google-map/google-map.component.ts
  src/services/direction.service.ts
Labels: Ready for review, bug, priority 3, risk: small

#174 Indoor directions/init hall8
  src/app/app.module.ts
  src/app/components/indoor/floor-plans/hall/h8/h8.component.html
  src/app/components/indoor/floor-plans/hall/h8/h8.component.scss
  src/app/components/indoor/floor-plans/hall/h8/h8.component.ts
  src/app/components/indoor/indoor-map/indoor-map.component.html
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.ts
  src/app/pages/indoor-view/indoor-view.page.html
  src/app/pages/indoor-view/indoor-view.page.ts
  src/global.scss
  src/services/indoorDirections.service.ts
Labels: Ready for review

#175 Enhancement/poi changements
  src/app/components/indoor/floor-plans/hall/h8/h8.component.ts
  src/app/components/outdoor/google-map/google-map.component.html
  src/app/components/outdoor/google-map/google-map.component.ts
  src/assets/icon/Marker_Coffee.png
  src/assets/icon/Marker_Drugstore.png
  src/assets/icon/Marker_Gas_Station.png
  src/assets/icon/Marker_Groceries.png
  src/assets/icon/Marker_Hotel.png
  src/assets/icon/Marker_Restaurant.png
  src/assets/icon/poi-marker.png
Labels: Ready for review, enhancement

#176 Bugfix/indoor input options
  package.json
  src/app/components/popovers/room-selector-popover/room-selector-popover.html
  src/app/components/popovers/room-selector-popover/room-selector-popover.scss
  src/app/components/popovers/room-selector-popover/room-selector-popover.ts
Labels: Ready for review, bug

#179 Bugfix/building info cancel button missing
  junit/TESTS-HeadlessChrome_80.0.3987_(Windows_10.0.0).xml
  src/app/components/outdoor/google-map/google-map.component.ts
  src/global.scss
Labels: Ready for review

#181 Enhancement/indoor directions algorithm
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.ts
  src/app/components/outdoor/google-map/google-map.component.spec.ts
  src/app/pages/indoor-view/indoor-view.page.html
  src/services/indoorDirections.service.ts
Labels: Ready for review, enhancement

#182 Issue171
  src/app/app.module.ts
  src/app/components/indoor/floor-plans/hall/h9/h9.component.html
  src/app/components/indoor/floor-plans/hall/h9/h9.component.scss
  src/app/components/indoor/floor-plans/hall/h9/h9.component.ts
  src/app/components/indoor/indoor-map/indoor-map.component.html
Labels: Ready for review, feature, help wanted

#183 Feature/164 switch route colors + time-footer/steps when user clicks on popup
  package.json
  src/app/components/outdoor/google-map/google-map.component.ts
Labels: Ready for review, priority 2, risk: small

#189 Feature/french translation
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/indoor/floor-plans/hall/h8/h8.component.ts
  src/app/components/indoor/floor-plans/hall/h9/h9.component.ts
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/popovers/poi-popover/poi-popover.component.html
  src/app/components/popovers/room-selector-popover/room-selector-popover.html
  src/app/components/popovers/room-selector-popover/room-selector-popover.ts
  src/app/components/popovers/search-popover/search-popover.component.html
  src/app/components/settings-options/settings-options.component.html
  src/app/components/settings-options/settings-options.component.ts
  src/app/components/settings-toolbar/settings-toolbar.component.html
  src/app/pages/indoor-view/indoor-view.page.ts
  src/app/pages/outdoor-view/outdoor-view.page.html
  src/app/pages/outdoor-view/outdoor-view.page.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/services/data-sharing.service.ts
  src/services/translation.service.spec.ts
  src/services/translation.service.ts
Labels: Ready for review, priority 3, risk: small

#191 Feature/directions manager
  src/app/app.module.ts
  src/app/components/indoor/floor-plans/hall/h8/h8.component.html
  src/app/components/indoor/floor-plans/hall/h8/h8.component.ts
  src/app/components/indoor/floor-plans/hall/h9/h9.component.html
  src/app/components/indoor/floor-plans/hall/h9/h9.component.scss
  src/app/components/indoor/floor-plans/hall/h9/h9.component.ts
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.ts
  src/app/components/indoor/indoor-map/indoor-map.component.html
  src/app/components/indoor/indoor-map/indoor-map.component.scss
  src/app/components/indoor/indoor-map/indoor-map.component.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.html
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.html
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.scss
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/popovers/info-popover/info-popover.component.html
  src/app/components/popovers/info-popover/info-popover.component.scss
  src/app/components/popovers/info-popover/info-popover.component.spec.ts
  src/app/components/popovers/info-popover/info-popover.component.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.html
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.scss
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.spec.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.ts
  src/app/components/popovers/search-popover/search-popover.component.ts
  src/app/components/popovers/time-footer/time-footer.component.html
  src/app/components/popovers/time-footer/time-footer.component.scss
  src/app/components/popovers/time-footer/time-footer.component.ts
  src/app/pages/indoor-view/indoor-view.page.html
  src/app/pages/indoor-view/indoor-view.page.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/services/directionsManager.service.ts
  src/services/stringHelper.service.ts
Labels: Ready for review, priority 1, risk: medium

#198 Bugfix/missing poi translation
  src/app/components/popovers/poi-popover/poi-popover.component.html
Labels: Ready for review, bug

#196 added room labels
  src/app/components/indoor/floor-plans/hall/h8/h8.component.html
  src/app/components/indoor/floor-plans/hall/h8/h8.component.scss
  src/app/components/indoor/floor-plans/hall/h9/h9.component.html
  src/app/components/indoor/floor-plans/hall/h9/h9.component.scss
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.html
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.scss
Labels: Ready for review

#199 added message to building popups to indicate a missing floor map
  src/app/components/outdoor/google-map/google-map.component.scss
  src/app/components/outdoor/google-map/google-map.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/global.scss
Labels: enhancement, priority 3, sprint 3

#201 Tests/unit tests for sprint 2 implementations
  src/app/components/indoor/floor-plans/hall/h8/h8.component.spec.ts
  src/app/components/indoor/floor-plans/hall/h9/h9.component.spec.ts
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.spec.ts
  src/app/components/indoor/indoor-map/indoor-map.component.spec.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.html
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.spec.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.spec.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.spec.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.spec.ts
  src/services/stringHelper.service.spec.ts
Labels: Ready for review, priority 2, risk: small, testing

#200 Issue58 - Google Account Integration
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/settings-options/settings-options.component.html
  src/app/components/settings-options/settings-options.component.ts
  src/services/google-oauth.service.spec.ts
  src/services/google-oauth.service.ts
Labels: Ready for review, feature, priority 2, risk: small

#203 Issue #156 - Search for and implement calendar library (UI)
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/popovers/calendar/calendar.component.html
  src/app/components/popovers/calendar/calendar.component.scss
  src/app/components/popovers/calendar/calendar.component.spec.ts
  src/app/components/popovers/calendar/calendar.component.ts
Labels: Ready for review, feature, priority 2, risk: medium

#206 Map sets proper zoom after search or campus change has been conducted
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
Labels: Ready for review, priority 2, risk: small

#207 Search bar is closing properly now if the user clicks outside the searchbar
  src/app/components/outdoor/google-map/google-map.component.html
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
Labels: Ready for review, priority 1, risk: small

#212 Tests/202 e2e use ids
  e2e/junit/junitresults.xml
  e2e/src/app.e2e-spec.ts
  package.json
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
Labels: priority 1, risk: small, testing

#220 Tests/145 sprint2 e2etests
  e2e/exception.png
  e2e/junit/junitresults.xml
  e2e/screenshots/BusScheduleTest
  e2e/screenshots/BusScheduleTest.png
  e2e/screenshots/OutdoorSearchTest.png
  e2e/screenshots/TitleTest.png
  e2e/screenshots/ToggleCampusTest.png
  e2e/screenshots/toandfromTest.png
  e2e/src/app.e2e-spec.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
Labels: Ready for review

#211 Issue #10: As a user, I am able to access and retrieve information from Google Calendar
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/popovers/calendar/calendar.component.html
  src/app/components/popovers/calendar/calendar.component.scss
  src/app/components/popovers/calendar/calendar.component.ts
  src/app/components/settings-options/settings-options.component.ts
  src/index.html
  src/main.ts
  src/services/google-oauth.service.ts
  src/services/httpclient.service.spec.ts
  src/services/httpclient.service.ts
Labels: Ready for review, feature, priority 3

#221 Feature/in and out directions
  package.json
  src/app/app-routing.module.ts
  src/app/components/indoor/floor-plans/hall/h8/h8.component.html
  src/app/components/indoor/floor-plans/hall/h8/h8.component.scss
  src/app/components/indoor/floor-plans/hall/h8/h8.component.ts
  src/app/components/indoor/floor-plans/hall/h9/h9.component.html
  src/app/components/indoor/floor-plans/hall/h9/h9.component.scss
  src/app/components/indoor/floor-plans/hall/h9/h9.component.ts
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.html
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.scss
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.ts
  src/app/components/indoor/indoor-map/indoor-map.component.scss
  src/app/components/indoor/indoor-map/indoor-map.component.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.html
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.scss
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.spec.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/indoor/indoor-time-of-arrival/indoor-time-of-arrival.component.html
  src/app/components/indoor/indoor-time-of-arrival/indoor-time-of-arrival.component.scss
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.html
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.ts
  src/app/components/popovers/time-footer/time-footer.component.html
  src/app/components/popovers/time-footer/time-footer.component.ts
  src/app/pages/indoor-view/indoor-view.page.scss
  src/app/pages/indoor-view/indoor-view.page.ts
  src/app/pages/outdoor-view/outdoor-view.page.ts
  src/services/directionsManager.service.ts
  src/services/indoorDirections.service.ts
  tsconfig.json
Labels: Ready for review, priority 1, risk: high, sprint 3
