Repository claudiiafg/MapConU, pull requests merged in 2020-02, with the labels that each got.

#66 Feature/11 google api
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.scss
  src/app/components/google-map/google-map.component.ts
Labels: feature

#69 Issue38 create landing page
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.html
  src/app/components/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.scss
  src/app/components/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.spec.ts
  src/app/components/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.scss
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.spec.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.scss
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.spec.ts
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/theme/variables.scss
Labels: Ready for review

#68 Integration/geolocation api
  config.xml
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.scss
  src/app/components/google-map/google-map.component.ts
  src/assets/icon/oakley-inc-logo-ray-ban-sunglasses-decal-blue-circle.jpg
  src/services/geolocationServices.ts
  src/theme/variables.scss
Labels: Ready for review

#75 Bugfix/geolocation updates
  GoogleService-Info.plist
  config.xml
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.ts
  src/assets/icon/position-marker.png
  src/environments/environment.ts
  src/services/geolocationServices.ts
Labels: Ready for review

#76 Feature/user accounts
  src/app/app.component.ts
  src/app/app.module.ts
  src/models/userModel.ts
  src/services/userServices.ts
Labels: Ready for review, sprint 1

#77 Integration/headlesstest
  e2e/protractor.conf.js
  karma.conf.js
  package-lock.json
  package.json
Labels: Ready for review

#78 Feature/29 add logo to assets
  e2e/protractor.conf.js
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.scss
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/search-popover/search-popover.component.html
  src/app/components/search-popover/search-popover.component.scss
  src/app/components/search-popover/search-popover.component.spec.ts
  src/assets/logo/MapConU_logo.png
  src/assets/logo/MapConU_logo.svg
  src/assets/shapes.svg
  src/environments/environment.ts
  src/models/userModel.ts
  src/services/data-sharing.service.ts
  src/services/geolocationServices.ts
  src/services/userServices.ts
  src/theme/variables.scss
Labels: Ready for review

#79 Added personalized app icon (ios & android)
  resources/android/icon/drawable-hdpi-icon.png
  resources/android/icon/drawable-ldpi-icon.png
  resources/android/icon/drawable-mdpi-icon.png
  resources/android/icon/drawable-xhdpi-icon.png
  resources/android/icon/drawable-xxhdpi-icon.png
  resources/android/icon/drawable-xxxhdpi-icon.png
  resources/ios/icon/icon-1024.png
  resources/ios/icon/icon-20.png
  resources/ios/icon/icon-20@2x.png
  resources/ios/icon/icon-20@3x.png
  resources/ios/icon/icon-24@2x.png
  resources/ios/icon/icon-27.5@2x.png
  resources/ios/icon/icon-29.png
  resources/ios/icon/icon-29@2x.png
  resources/ios/icon/icon-29@3x.png
  resources/ios/icon/icon-40.png
  resources/ios/icon/icon-40@2x.png
  resources/ios/icon/icon-40@3x.png
  resources/ios/icon/icon-44@2x.png
  resources/ios/icon/icon-50.png
  resources/ios/icon/icon-50@2x.png
  resources/ios/icon/icon-60.png
  resources/ios/icon/icon-60@2x.png
  resources/ios/icon/icon-60@3x.png
  resources/ios/icon/icon-72.png
  resources/ios/icon/icon-72@2x.png
  resources/ios/icon/icon-76.png
  resources/ios/icon/icon-76@2x.png
  resources/ios/icon/icon-83.5@2x.png
  resources/ios/icon/icon-86@2x.png
  resources/ios/icon/icon-98@2x.png
  resources/ios/icon/icon-small.png
  resources/ios/icon/icon-small@2x.png
  resources/ios/icon/icon-small@3x.png
  resources/ios/icon/icon.png
  resources/ios/icon/icon@2x.png
  src/assets/icon/oakley-inc-logo-ray-ban-sunglasses-decal-blue-circle.jpg
Labels: Ready for review, risk: small, sprint 1

#97 Fix search popover, map size
  src/app/components/google-map/google-map.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/theme/variables.scss
Labels: Ready for review

#84 Settings and indoor nav toolbars
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.html
  src/app/components/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.scss
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.html
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.scss
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.spec.ts
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.scss
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.scss
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/settings-toolbar/settings-toolbar.component.html
  src/app/components/settings-toolbar/settings-toolbar.component.scss
  src/app/components/settings-toolbar/settings-toolbar.component.spec.ts
  src/app/components/settings-toolbar/settings-toolbar.component.ts
  src/global.scss
Labels: Ready for review

#105 Bugfix/104 popover style
  package.json
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.ts
  src/app/components/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.scss
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.html
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.scss
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.spec.ts
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.scss
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/settings-toolbar/settings-toolbar.component.html
  src/app/components/settings-toolbar/settings-toolbar.component.scss
  src/app/components/settings-toolbar/settings-toolbar.component.spec.ts
  src/app/components/settings-toolbar/settings-toolbar.component.ts
  src/global.scss
Labels: Ready for review, priority 1, risk: small, sprint 2

#106 Issue80 mark and highlight con u buildings
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.ts
Labels: Ready for review

#116 Feature/outdoor points of interest
  config.xml
  package.json
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/poi-popover/poi-popover.component.html
  src/app/components/poi-popover/poi-popover.component.scss
  src/app/components/poi-popover/poi-popover.component.spec.ts
  src/app/components/poi-popover/poi-popover.component.ts
  src/assets/icon/poi-marker.png
  src/global.scss
  src/services/geolocationServices.ts
  src/services/poiServices.ts
Labels: Ready for review, feature, sprint 2

#123 Issue94 building info boxes
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.scss
  src/app/components/google-map/google-map.component.ts
  src/app/components/indoor-map/indoor-map.component.html
  src/app/components/indoor-map/indoor-map.component.scss
  src/app/components/indoor-map/indoor-map.component.spec.ts
  src/app/components/indoor-map/indoor-map.component.ts
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.html
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.scss
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/poi-popover/poi-popover.component.html
  src/app/components/poi-popover/poi-popover.component.scss
  src/app/components/poi-popover/poi-popover.component.ts
  src/app/floor-plans/jmsb/mb1/mb1.html
  src/app/floor-plans/jmsb/mb1/mb1.scss
  src/app/floor-plans/jmsb/mb1/mb1.ts
  src/app/pages/indoor-view/indoor-view-routing.module.ts
  src/app/pages/indoor-view/indoor-view.module.ts
  src/app/pages/indoor-view/indoor-view.page.html
  src/app/pages/indoor-view/indoor-view.page.scss
  src/app/pages/indoor-view/indoor-view.page.spec.ts
  src/app/pages/indoor-view/indoor-view.page.ts
  src/app/pages/outdoor-view/outdoor-view-routing.module.ts
  src/app/pages/outdoor-view/outdoor-view.module.ts
  src/app/pages/outdoor-view/outdoor-view.page.html
  src/app/pages/outdoor-view/outdoor-view.page.scss
  src/app/pages/outdoor-view/outdoor-view.page.spec.ts
  src/app/pages/outdoor-view/outdoor-view.page.ts
  src/assets/floor-plans/Hall-8.svg
  src/assets/floor-plans/Hall-9.svg
  src/assets/floor-plans/MB-1.svg
  src/assets/floor-plans/MB-S2.svg
  src/assets/floor-plans/VL-1.svg
  src/assets/floor-plans/VL-2.svg
  src/assets/icon/logo_as_marker.png
  src/global.scss
  src/services/geolocationServices.ts
  src/services/poiServices.ts
Labels: Ready for review, priority 1

#124 Feature/5 user time steps
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/google-map/google-map.component.html
  src/app/components/google-map/google-map.component.ts
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.html
  src/app/components/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/modal-directions/modal-directions.component.html
  src/app/components/modal-directions/modal-directions.component.scss
  src/app/components/modal-directions/modal-directions.component.spec.ts
  src/app/components/modal-directions/modal-directions.component.ts
  src/app/components/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.scss
  src/app/components/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/poi-popover/poi-popover.component.ts
  src/app/components/search-popover/search-popover.component.html
  src/app/components/search-popover/search-popover.component.ts
  src/app/components/time-footer/time-footer.component.html
  src/app/components/time-footer/time-footer.component.scss
  src/app/components/time-footer/time-footer.component.spec.ts
  src/app/components/time-footer/time-footer.component.ts
  src/app/pages/outdoor-view/outdoor-view.module.ts
  src/app/pages/outdoor-view/outdoor-view.page.html
  src/services/data-sharing.service.ts
  src/services/direction.service.spec.ts
  src/services/direction.service.ts
  src/services/poiServices.ts
  src/services/search.service.ts
  src/services/userServices.ts
Labels: Ready for review, priority 1
