Repository claudiiafg/MapConU, pull requests merged in 2020-04, with the labels that each got.

#280 feature/261-added straight arrow + smaller x button
  src/app/components/outdoor/modal-directions/modal-directions.component.html
  src/app/components/outdoor/modal-directions/modal-directions.component.scss
  src/services/direction.service.ts
Labels: Ready for review, enhancement

#279 Bugfix/197- outdoor to indoors footer
  src/app/components/popovers/time-footer/time-footer.component.html
  src/app/components/popovers/time-footer/time-footer.component.ts
Labels: Ready for review

#281 Issue #275 - Calendar performance issues
  src/app/components/popovers/calendar/calendar.component.ts
  src/global.scss
Labels: Ready for review, enhancement, priority 3, risk: small

#286 Issue #274: Login to our google accounts in the calendar view
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.html
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.ts
  src/app/components/popovers/calendar/calendar.component.html
  src/app/components/popovers/calendar/calendar.component.scss
  src/app/components/popovers/calendar/calendar.component.ts
Labels: Ready for review, enhancement, priority 3, risk: small

#284 Feature 25 : Add speach to text for search bar
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.scss
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/global.scss
Labels: Ready for review, feature

#205 Feature/backbutton exit
  src/app/app.component.ts
  src/app/components/outdoor/google-map/google-map.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: enhancement, priority 3, risk: small

#292 Bugfix/css fixes
  package-lock.json
  package.json
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.html
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.scss
  src/app/components/indoor/indoor-time-of-arrival/indoor-time-of-arrival.component.scss
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.scss
  src/app/components/popovers/calendar/calendar.component.html
  src/app/components/popovers/calendar/calendar.component.ts
  src/app/components/settings-options/settings-options.component.html
  src/app/components/settings-options/settings-options.component.scss
  src/app/components/settings-toolbar/settings-toolbar.component.html
  src/app/components/settings-toolbar/settings-toolbar.component.scss
  src/app/pages/indoor-view/indoor-view.page.scss
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/polyfills.ts
Labels: Ready for review, bug

#296 Issue/210 Changed the icon + added center location button
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
Labels: Ready for review

#293 Feature: 128 directions with calendar
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/outdoor/google-map/google-map.component.spec.ts
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/popovers/calendar/calendar.component.ts
  src/app/components/popovers/time-footer/time-footer.component.html
  src/app/components/popovers/time-footer/time-footer.component.ts
  src/models/buildinginfo.spec.ts
  src/models/buildinginfo.ts
  src/models/calendarEventClickedModel.ts
  src/models/coordinates.spec.ts
  src/models/coordinates.ts
  src/models/directionModel.ts
  src/services/direction.service.ts
  src/services/directionsManager.service.ts
  src/services/sqlite.service.ts
Labels: Ready for review

#294 Feature/266: The user can click on any poi on the map and create a route to the selected location
  src/app/components/outdoor/google-map/google-map.component.html
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.scss
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: Conflicting files, Ready for review

#295 Bugfix/residual data
  src/app/components/indoor/floor-plans/hall/h8/h8.component.ts
  src/app/components/indoor/floor-plans/hall/h9/h9.component.ts
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.ts
  src/app/components/indoor/indoor-map/indoor-map.component.ts
  src/app/components/outdoor/google-map/extraInfo.ts
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.ts
  src/app/components/popovers/time-footer/time-footer.component.ts
  src/app/pages/indoor-view/indoor-view.page.ts
  src/services/directionsManager.service.ts
Labels: Conflicting files, Ready for review, bug

#298 fixed broken buildingToBuilding functions - closes #297
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/services/directionsManager.service.ts
Labels: Ready for review, bug

#300 187/hide side buttons 3d view
  src/app/components/outdoor/google-map/google-map.component.html
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/pages/outdoor-view/outdoor-view.page.html
  src/app/pages/outdoor-view/outdoor-view.page.ts
  src/services/data-sharing.service.ts
Labels: Ready for review, risk: small

#301 Issue273: Google calendar in ios
  angular.json
  config.xml
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/popovers/calendar/calendar.component.html
  src/app/components/popovers/calendar/calendar.component.scss
  src/app/components/popovers/calendar/calendar.component.ts
  src/app/components/popovers/display-calendars-popover/display-calendars-popover.component.html
  src/app/components/popovers/display-calendars-popover/display-calendars-popover.component.scss
  src/app/components/popovers/display-calendars-popover/display-calendars-popover.component.spec.ts
  src/app/components/popovers/display-calendars-popover/display-calendars-popover.component.ts
  src/services/google-oauth.service.ts
  src/services/httpclient.service.ts
Labels: Ready for review, bug

#304 290: Added TypeDoc descriptions
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.ts
  src/app/components/popovers/indoor-poi-popover/indoor-poi-popover.component.ts
  src/app/components/settings-options/settings-options.component.ts
  src/app/components/settings-toolbar/settings-toolbar.component.ts
  src/app/pages/indoor-view/indoor-view.page.ts
  src/services/data-sharing.service.ts
  src/services/geolocation.services.ts
  src/services/indoor-poi.service.ts
  src/services/translation.service.ts
Labels: Ready for review, documentation

#307 option to toggle for person with disability
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.html
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.scss
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/assets/icon/Disability.png
  src/services/directionsManager.service.ts
Labels: enhancement, priority 2, sprint 4

#305 Feature/loyola indoor plans
  package.json
  src/app/app.module.ts
  src/app/components/indoor/floor-plans/varnier/vl1/vl1.component.html
  src/app/components/indoor/floor-plans/varnier/vl1/vl1.component.scss
  src/app/components/indoor/floor-plans/varnier/vl1/vl1.component.spec.ts
  src/app/components/indoor/floor-plans/varnier/vl1/vl1.component.ts
  src/app/components/indoor/indoor-map/indoor-map.component.html
  src/app/components/indoor/indoor-map/indoor-map.component.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.ts
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/popovers/indoor-poi-popover/indoor-poi-popover.component.html
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/services/directionsManager.service.ts
  src/services/indoorDirections.service.ts
  src/services/stringHelper.service.ts
Labels: Ready for review, bug, enhancement, feature, priority 1

#309 Bugfix/sonar qube issues
  src/app/components/indoor/floor-plans/hall/h8/h8.component.html
  src/app/components/outdoor/google-map/google-map.component.ts
  src/app/components/popovers/calendar/calendar.component.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.html
  src/app/pages/outdoor-view/outdoor-view.page.ts
  src/services/translation.service.ts
Labels: Ready for review, bug

#311 Tests/sprint 2 unit test implementation outdoor
  junit/TESTS-HeadlessChrome_80.0.3987_(Windows_10.0.0).xml
  package.json
  src/app/components/indoor/floor-plans/hall/h8/h8.component.spec.ts
  src/app/components/indoor/floor-plans/hall/h9/h9.component.spec.ts
  src/app/components/indoor/floor-plans/jmsb/mb1/mb1.component.spec.ts
  src/app/components/indoor/indoor-map/indoor-map.component.spec.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.spec.ts
  src/app/components/indoor/indoor-navigation-toolbar/indoor-navigation-toolbar.component.spec.ts
  src/app/components/indoor/indoor-time-of-arrival/indoor-time-of-arrival.component.spec.ts
  src/app/components/outdoor/google-map/google-map.component.spec.ts
  src/app/components/outdoor/modal-directions/modal-directions.component.html
  src/app/components/outdoor/modal-directions/modal-directions.component.spec.ts
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.html
  src/app/components/outdoor/outdoor-navigation-side-buttons/outdoor-navigation-side-buttons.component.spec.ts
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.html
  src/app/components/outdoor/outdoor-navigation-toolbar/outdoor-navigation-toolbar.component.spec.ts
  src/app/components/popovers/calendar/calendar.component.spec.ts
  src/app/components/popovers/display-calendars-popover/display-calendars-popover.component.spec.ts
  src/app/components/popovers/indoor-poi-popover/indoor-poi-popover.component.spec.ts
  src/app/components/popovers/info-popover/info-popover.component.spec.ts
  src/app/components/popovers/poi-popover/poi-popover.component.spec.ts
  src/app/components/popovers/room-selector-popover/room-selector-popover.component.spec.ts
  src/app/components/popovers/search-popover/search-popover.component.spec.ts
  src/app/components/popovers/time-footer/time-footer.component.spec.ts
  src/app/components/settings-options/settings-options.component.html
  src/app/components/settings-options/settings-options.component.spec.ts
  src/app/components/settings-toolbar/settings-toolbar.component.spec.ts
  src/app/pages/indoor-view/indoor-view.page.spec.ts
  src/app/pages/outdoor-view/outdoor-view.page.spec.ts
  src/app/test/dummy.spec.ts
  src/services/data-sharing.service.spec.ts
  src/services/direction.service.spec.ts
  src/services/directionsManager.service.spec.ts
  src/services/geolocation.services.spec.ts
  src/services/google-oauth.service.spec.ts
  src/services/google-oauth.service.ts
  src/services/httpclient.service.spec.ts
  src/services/indoor-poi.service.spec.ts
  src/services/indoorDirections.service.spec.ts
  src/services/indoorDirections.service.ts
  src/services/poi.services.spec.ts
  src/services/sqlite.service.spec.ts
  src/services/stringHelper.service.spec.ts
  src/services/translation.service.spec.ts
  src/services/translation.service.ts
  src/services/user.services.spec.ts
  src/services/user.services.ts
Labels: priority 2, risk: small, testing

#310 Bugfix/indoor directions
  src/app/components/indoor/floor-plans/hall/h9/h9.component.html
  src/app/components/indoor/indoor-map/indoor-map.component.ts
  src/app/components/indoor/indoor-navigation-side-buttons/indoor-navigation-side-buttons.component.ts
  src/services/directionsManager.service.ts
  src/services/indoorDirections.service.ts
Labels: Ready for review, bug
